export enum Competency {
    DIGITAL_LITERACY = "Digital Literacy",
    DIGITAL_COMMUNICATION = "Digital Communication",
    ONLINE_SAFETY = "Online Safety",
    INFORMATION_SEARCH = "Information Search",
    DATA_INTERPRETATION = "Data Interpretation",
    BASIC_COMPUTING = "Basic Computing",
    DOCUMENT_CREATION = "Document Creation",
    SPREADSHEET_SKILLS = "Spreadsheet Skills",
    PRESENTATION_SKILLS = "Presentation Skills",
    EMAIL_ETIQUETTE = "Email Etiquette",
    CRITICAL_THINKING = "Critical Thinking",
    PROBLEM_SOLVING = "Problem Solving",
    LOGICAL_REASONING = "Logical Reasoning",
    NUMERICAL_REASONING = "Numerical Reasoning",
    READING_COMPREHENSION = "Reading Comprehension",
    LISTENING_SKILLS = "Listening Skills",
    GRAMMAR_AND_LANGUAGE = "Grammar and Language",
    VOCABULARY = "Vocabulary",
    TIME_MANAGEMENT = "Time Management",
    TEAMWORK = "Teamwork",
    CREATIVE_THINKING = "Creative Thinking",
    ADAPTABILITY = "Adaptability"
}
